<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Industry40DT">
  <eSubpackages name="Robot">
    <eClassifiers xsi:type="ecore:EClass" name="Robot">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Camera"/>
    <eClassifiers xsi:type="ecore:EClass" name="Gripper"/>
    <eClassifiers xsi:type="ecore:EClass" name="Joint"/>
  </eSubpackages>
  <eSubpackages name="Conveyor">
    <eClassifiers xsi:type="ecore:EClass" name="Conveyor">
      <eAnnotations>
        <details key="type" value="DT"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isRunning" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="elementsProcessed" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="timeSinceCounterReset"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IRSensor">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="itemDetected" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="ProductionLine">
    <eClassifiers xsi:type="ecore:EClass" name="ProductionLine">
      <eStructuralFeatures xsi:type="ecore:EReference" name="robots" upperBound="-1"
          eType="#//Robot/Robot" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="conveyors" upperBound="-1"
          eType="#//Conveyor/Conveyor" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="itemsProcessed" upperBound="-1"
          eType="#//Item/Item" containment="true"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="Item">
    <eClassifiers xsi:type="ecore:EClass" name="Item">
      <eAnnotations>
        <details key="type" value="DT"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="leadTime">
        <eAnnotations>
          <details key="type" value="DT"/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
